openapi: 3.0.2
info:
  title: Trenes Argentinos API
  version: x.x.x
servers:
  - url: https://api-servicios.sofse.gob.ar
    description: Horarios
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: authorization

paths:
  /v1/infraestructura/gerencias:
    get:
      security:
        - ApiKeyAuth: []
      summary: GET líneas de tren
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 11
                    id_empresa:
                      type: integer
                      example: 1
                    nombre:
                      type: string
                      example: "Roca"
                    estado:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 13
                        mensaje:
                          type: string
                          example: "Alertas por ramal"
                        color:
                          type: string
                          example: "#435a6c"
                    alerta:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: integer
                            example: 13
                          mensaje:
                            type: string
                            example: "Sarmiento anda mal"
                          color:
                            type: string
                            example: "#435a6c"
                  required:
                    - id
                    - id_empresa
                    - nombre
                    - estado
                    - alerta
              example:
                - id: 11
                  id_empresa: 1
                  nombre: "Roca"
                  estado:
                    id: 13
                    mensaje: "Alertas por ramal"
                    color: "#435a6c"
                  alerta: []
                - id: 12
                  id_empresa: 1
                  nombre: "Sarmiento"
                  estado:
                    id: 13
                    mensaje: "Alertas por ramal"
                    color: "#435a6c"
                  alerta:
                    - id: 13
                      mensaje: "Sarmiento anda mal"
                      color: "#435a6c"
        "401":
          description: Unauthorized access
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 401
                  message:
                    type: string
                    example: "Unauthorized"
                required:
                  - status
                  - message
      parameters:
        - name: idEmpresa
          in: query
          required: false
          schema:
            type: number

  /v1/infraestructura/ramales:
    get:
      security:
        - ApiKeyAuth: []
      summary: GET ramales

      responses:
        "200":
          description: A successful response containing an array of ramales
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 17
                    id_estacion_inicial:
                      type: integer
                      example: 93
                    id_estacion_final:
                      type: integer
                      example: 13
                    id_gerencia:
                      type: integer
                      example: 11
                    nombre:
                      type: string
                      example: "Constitución-Alejandro Korn"
                    estaciones:
                      type: integer
                      example: 15
                    operativo:
                      type: integer
                      example: 1
                    es_electrico:
                      type: integer
                      example: 1
                    tipo_id:
                      type: integer
                      example: 1
                    puntualidad_tolerancia:
                      type: integer
                      example: 359
                    siglas:
                      type: string
                      example: "AK"
                    publico:
                      type: boolean
                      example: true
                    orden_ramal:
                      type: integer
                      example: 1
                    mostrar_en_panel_cumplimiento:
                      type: boolean
                      example: true
                    cabecera_inicial:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 93
                        nombre:
                          type: string
                          example: "Constitución"
                        siglas:
                          type: string
                          example: "PC"
                        nombre_corto:
                          type: string
                          example: "Plaza C."
                        visibilidad:
                          type: string
                          example: '{"totem": "1", "app_mobile": "1"}'
                    cabecera_final:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 13
                        nombre:
                          type: string
                          example: "Alejandro Korn"
                        siglas:
                          type: string
                          example: "AK"
                        nombre_corto:
                          type: string
                          example: "A. Korn"
                        visibilidad:
                          type: string
                          example: '{"totem": "1", "app_mobile": "1"}'
                    alerta:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: integer
                            example: 68281
                          linea_id:
                            type: integer
                            example: 11
                          ramal_id:
                            type: integer
                            example: 15
                          estacion_id:
                            type: integer
                            nullable: true
                          sentido:
                            type: string
                            example: "1"
                          causa_gtfs:
                            type: string
                            example: "OTHER_CAUSE"
                          efecto_gtfs:
                            type: string
                            example: "OTHER_EFFECT"
                          icono_fontawesome:
                            type: string
                            example: "fa-warning"
                          contenido:
                            type: string
                            example: "De lunes a viernes el último tren de Plaza Constitución a Bosques – T sale a las 21:34 h por obras. "
                          habilitado:
                            type: integer
                            example: 1
                          vigencia_desde:
                            type: string
                            format: date-time
                            example: "2025-01-07T14:26:00"
                          vigencia_hasta:
                            type: string
                            format: date-time
                            nullable: true
                          criticidad_orden:
                            type: integer
                            example: 4
                          criticidad_color_fondo:
                            type: string
                            example: "#dff0d8"
                          criticidad_color_texto:
                            type: string
                            example: "#3c763d"
                  required:
                    - id
                    - id_estacion_inicial
                    - id_estacion_final
                    - id_gerencia
                    - nombre
                    - estaciones
                    - operativo
                    - es_electrico
                    - tipo_id
                    - puntualidad_tolerancia
                    - siglas
                    - publico
                    - orden_ramal
                    - mostrar_en_panel_cumplimiento
                    - cabecera_inicial
                    - cabecera_final
                    - alerta
              example:
                - id: 17
                  id_estacion_inicial: 93
                  id_estacion_final: 13
                  id_gerencia: 11
                  nombre: "Constitución-Alejandro Korn"
                  estaciones: 15
                  operativo: 1
                  es_electrico: 1
                  tipo_id: 1
                  puntualidad_tolerancia: 359
                  siglas: "AK"
                  publico: true
                  orden_ramal: 1
                  mostrar_en_panel_cumplimiento: true
                  cabecera_inicial:
                    id: 93
                    nombre: "Constitución"
                    siglas: "PC"
                    nombre_corto: "Plaza C."
                    visibilidad: '{"totem": "1", "app_mobile": "1"}'
                  cabecera_final:
                    id: 13
                    nombre: "Alejandro Korn"
                    siglas: "AK"
                    nombre_corto: "A. Korn"
                    visibilidad: '{"totem": "1", "app_mobile": "1"}'
                  alerta: null
                - id: 13
                  id_estacion_inicial: 93
                  id_estacion_final: 43
                  id_gerencia: 11
                  nombre: "Constitución-Bosques-Q"
                  estaciones: 14
                  operativo: 1
                  es_electrico: 1
                  tipo_id: 1
                  puntualidad_tolerancia: 359
                  siglas: "BQ-Q"
                  publico: true
                  orden_ramal: 1
                  mostrar_en_panel_cumplimiento: true
                  cabecera_inicial:
                    id: 93
                    nombre: "Constitución"
                    siglas: "PC"
                    nombre_corto: "Plaza C."
                    visibilidad: '{"totem": "1", "app_mobile": "1"}'
                  cabecera_final:
                    id: 43
                    nombre: "Bosques"
                    siglas: "BQ"
                    nombre_corto: "Bosques"
                    visibilidad: '{"totem": "1", "app_mobile": "1"}'
                  alerta: null
                - id: 15
                  id_estacion_inicial: 93
                  id_estacion_final: 43
                  id_gerencia: 11
                  nombre: "Constitución-Bosques-T"
                  estaciones: 12
                  operativo: 1
                  es_electrico: 1
                  tipo_id: 1
                  puntualidad_tolerancia: 359
                  siglas: "BQ-T"
                  publico: true
                  orden_ramal: 1
                  mostrar_en_panel_cumplimiento: true
                  cabecera_inicial:
                    id: 93
                    nombre: "Constitución"
                    siglas: "PC"
                    nombre_corto: "Plaza C."
                    visibilidad: '{"totem": "1", "app_mobile": "1"}'
                  cabecera_final:
                    id: 43
                    nombre: "Bosques"
                    siglas: "BQ"
                    nombre_corto: "Bosques"
                    visibilidad: '{"totem": "1", "app_mobile": "1"}'
                  alerta:
                    - id: 68281
                      linea_id: 11
                      ramal_id: 15
                      estacion_id: null
                      sentido: "1"
                      causa_gtfs: "OTHER_CAUSE"
                      efecto_gtfs: "OTHER_EFFECT"
                      icono_fontawesome: "fa-warning"
                      contenido: "De lunes a viernes el último tren de Plaza Constitución a Bosques – T sale a las 21:34 h por obras."
                      habilitado: 1
                      vigencia_desde: "2025-01-07T14:26:00"
                      vigencia_hasta: null
                      criticidad_orden: 4
                      criticidad_color_fondo: "#dff0d8"
                      criticidad_color_texto: "#3c763d"
                    - id: 68283
                      linea_id: 11
                      ramal_id: 15
                      estacion_id: null
                      sentido: "2"
                      causa_gtfs: "OTHER_CAUSE"
                      efecto_gtfs: "OTHER_EFFECT"
                      icono_fontawesome: "fa-warning"
                      contenido: "De lunes a viernes el último tren de Bosques – T a Plaza Constitución sale a las 22:02 h y de Bosques a Temperley a las 22:36 h por obras."
                      habilitado: 1
                      vigencia_desde: "2025-01-07T14:28:00"
                      vigencia_hasta: null
                      criticidad_orden: 4
                      criticidad_color_fondo: "#dff0d8"
                      criticidad_color_texto: "#3c763d"
        "401":
          description: Unauthorized access
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 401
                  message:
                    type: string
                    example: "Unauthorized"
                required:
                  - status
                  - message
      parameters:
        - name: idGerencia
          in: query
          required: false
          schema:
            type: number

  /v1/infraestructura/estaciones:
    get:
      summary: GET estaciones
      security:
        - ApiKeyAuth: []
      responses:
        "200":
          description: A successful response containing an array of estaciones
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    nombre:
                      type: string
                      example: "Bernal"
                    id_estacion:
                      type: string
                      example: "39"
                    id_tramo:
                      type: string
                      example: "21"
                    orden:
                      type: string
                      example: "5"
                    id_referencia:
                      type: string
                      example: "11177"
                    latitud:
                      type: string
                      format: float
                      example: "-34.7093395"
                    longitud:
                      type: string
                      format: float
                      example: "-58.2803725"
                    referencia_orden:
                      type: string
                      example: "727"
                    radio:
                      type: string
                      example: ""
                    andenes_habilitados:
                      type: string
                      example: "2"
                    visibilidad:
                      type: object
                      properties:
                        totem:
                          type: integer
                          example: 1
                        app_mobile:
                          type: integer
                          example: 1
                    incluida_en_ramales:
                      type: array
                      items:
                        type: integer
                      example: [13, 11]
                    operativa_en_ramales:
                      type: array
                      items:
                        type: integer
                      example: [13, 11]
                  required:
                    - nombre
                    - id_estacion
                    - id_tramo
                    - orden
                    - id_referencia
                    - latitud
                    - longitud
                    - referencia_orden
                    - andenes_habilitados
                    - visibilidad
                    - incluida_en_ramales
                    - operativa_en_ramales
              example:
                - nombre: "Bernal"
                  id_estacion: "39"
                  id_tramo: "21"
                  orden: "5"
                  id_referencia: "11177"
                  latitud: "-34.7093395"
                  longitud: "-58.2803725"
                  referencia_orden: "727"
                  radio: ""
                  andenes_habilitados: "2"
                  visibilidad:
                    totem: 1
                    app_mobile: 1
                  incluida_en_ramales: [13, 11]
                  operativa_en_ramales: [13, 11]
        "401":
          description: Unauthorized access
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 401
                  message:
                    type: string
                    example: "Unauthorized"
                required:
                  - status
                  - message
      parameters:
        - name: idGerencia
          in: query
          required: false
          schema:
            type: number
        - name: nombre
          in: query
          required: false
          schema:
            type: string

  /v1/arribos/estacion/{id}:
    get:
      summary: GET estacion by id
      security:
        - ApiKeyAuth: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  timestamp:
                    type: integer
                    description: Timestamp of the response
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        arribo:
                          type: object
                          properties:
                            anden:
                              type: object
                              properties:
                                id:
                                  type: integer
                                nombre:
                                  type: string
                            orden:
                              type: integer
                            equipo:
                              type: object
                              properties:
                                id:
                                  type: integer
                                gpss:
                                  type: array
                                  items:
                                    type: string
                                nombre:
                                  type: string
                                esElectrico:
                                  type: integer
                            nombre:
                              type: string
                            parada:
                              type: boolean
                            salida:
                              type: object
                              properties:
                                programada:
                                  type: string
                                  format: date-time
                                estimada:
                                  type: string
                                  format: date-time
                            idPunto:
                              type: integer
                            llegada:
                              type: object
                              properties:
                                programada:
                                  type: string
                                  format: date-time
                                estimada:
                                  type: string
                                  format: date-time
                            idElemento:
                              type: integer
                            programada:
                              type: boolean
                            segundos:
                              type: integer
                        servicio:
                          type: object
                          properties:
                            numero:
                              type: integer
                            ramal:
                              type: object
                              properties:
                                id:
                                  type: integer
                                nombre:
                                  type: string
                                tolerancia:
                                  type: integer
                                cabeceraFinal:
                                  type: object
                                  properties:
                                    id:
                                      type: integer
                                    nombre:
                                      type: string
                                    nombreCorto:
                                      type: string
                                cabeceraInicial:
                                  type: object
                                  properties:
                                    id:
                                      type: integer
                                    nombre:
                                      type: string
                                    nombreCorto:
                                      type: string
                            gerencia:
                              type: object
                              properties:
                                id:
                                  type: integer
                                nombre:
                                  type: string
                            cancelacion:
                              type: string
                            equipo:
                              type: object
                              properties:
                                id:
                                  type: integer
                                gpss:
                                  type: array
                                  items:
                                    type: string
                                nombre:
                                  type: string
                                esElectrico:
                                  type: integer
                            oculto:
                              type: boolean
                            sentido:
                              type: integer
                            tipo:
                              type: object
                              properties:
                                id:
                                  type: integer
                                nombre:
                                  type: string
                                programado:
                                  type: boolean
                                clasificacion:
                                  type: object
                                  properties:
                                    id:
                                      type: integer
                                    nombre:
                                      type: string
                                subclasificacion:
                                  type: integer
                            leyenda:
                              type: string
                            location:
                              type: object
                              properties:
                                lat:
                                  type: number
                                  format: float
                                long:
                                  type: number
                                  format: float
                            id:
                              type: string
                            desde:
                              type: object
                              properties:
                                estacion:
                                  type: object
                                  properties:
                                    tipo:
                                      type: object
                                      properties:
                                        id:
                                          type: integer
                                        nombre:
                                          type: string
                                    anden:
                                      type: object
                                      properties:
                                        id:
                                          type: integer
                                        nombre:
                                          type: string
                                    orden:
                                      type: integer
                                    tramo:
                                      type: object
                                      properties:
                                        id:
                                          type: integer
                                        orden:
                                          type: integer
                                    equipo:
                                      type: object
                                      properties:
                                        id:
                                          type: integer
                                        nombre:
                                          type: string
                                    nombre:
                                      type: string
                                    parada:
                                      type: boolean
                                    salida:
                                      type: object
                                      properties:
                                        programada:
                                          type: string
                                          format: date-time
                                        ultimaHoraRegistrada:
                                          type: string
                                          format: date-time
                                        distancia:
                                          type: number
                                          format: float
                                        velocidad:
                                          type: number
                                          format: float
                                        latitud:
                                          type: number
                                          format: float
                                        longitud:
                                          type: number
                                          format: float
                                        referencia:
                                          type: integer
                                        real:
                                          type: string
                                          format: date-time
                                    idPunto:
                                      type: integer
                                    llegada:
                                      type: object
                                    idElemento:
                                      type: integer
                                    programada:
                                      type: boolean
                                punto:
                                  type: object
                                  properties:
                                    tipo:
                                      type: object
                                      properties:
                                        id:
                                          type: integer
                                        nombre:
                                          type: string
                                    anden:
                                      type: object
                                      properties:
                                        id:
                                          type: integer
                                        nombre:
                                          type: string
                                    orden:
                                      type: integer
                                    tramo:
                                      type: object
                                      properties:
                                        id:
                                          type: integer
                                        orden:
                                          type: integer
                                    equipo:
                                      type: object
                                      properties:
                                        id:
                                          type: integer
                                        nombre:
                                          type: string
                                    nombre:
                                      type: string
                                    parada:
                                      type: boolean
                                    salida:
                                      type: object
                                      properties:
                                        programada:
                                          type: string
                                          format: date-time
                                        estimada:
                                          type: string
                                          format: date-time
                                    idPunto:
                                      type: integer
                                    llegada:
                                      type: object
                                      properties:
                                        programada:
                                          type: string
                                          format: date-time
                                        estimada:
                                          type: string
                                          format: date-time
                                    idElemento:
                                      type: integer
                                    programada:
                                      type: boolean
                                estado:
                                  type: object
                                  properties:
                                    id:
                                      type: integer
                                    nombre:
                                      type: string
                            hasta:
                              type: object
                              properties:
                                estacion:
                                  type: object
                                  properties:
                                    tipo:
                                      type: object
                                      properties:
                                        id:
                                          type: integer
                                        nombre:
                                          type: string
                                    anden:
                                      type: object
                                      properties:
                                        id:
                                          type: integer
                                        nombre:
                                          type: string
                                    orden:
                                      type: integer
                                    tramo:
                                      type: object
                                      properties:
                                        id:
                                          type: integer
                                        orden:
                                          type: integer
                                    equipo:
                                      type: object
                                      properties:
                                        id:
                                          type: integer
                                        gpss:
                                          type: array
                                          items:
                                            type: string
                                        nombre:
                                          type: string
                                        esElectrico:
                                          type: integer
                                    nombre:
                                      type: string
                                    parada:
                                      type: boolean
                                    salida:
                                      type: object
                                      properties:
                                        programada:
                                          type: string
                                          format: date-time
                                        estimada:
                                          type: string
                                          format: date-time
                                    idPunto:
                                      type: integer
                                    llegada:
                                      type: object
                                      properties:
                                        programada:
                                          type: string
                                          format: date-time
                                        estimada:
                                          type: string
                                          format: date-time
                                    idElemento:
                                      type: integer
                                    programada:
                                      type: boolean
                                punto:
                                  type: object
                                  properties:
                                    tipo:
                                      type: object
                                      properties:
                                        id:
                                          type: integer
                                        nombre:
                                          type: string
                                    orden:
                                      type: integer
                                    tramo:
                                      type: object
                                      properties:
                                        id:
                                          type: integer
                                        orden:
                                          type: integer
                                    equipo:
                                      type: object
                                      properties:
                                        id:
                                          type: integer
                                        gpss:
                                          type: array
                                          items:
                                            type: string
                                        nombre:
                                          type: string
                                        esElectrico:
                                          type: integer
                                    nombre:
                                      type: string
                                    parada:
                                      type: boolean
                                    salida:
                                      type: object
                                      properties:
                                        programada:
                                          type: string
                                          format: date-time
                                        estimada:
                                          type: string
                                          format: date-time
                                    idPunto:
                                      type: integer
                                    llegada:
                                      type: object
                                      properties:
                                        programada:
                                          type: string
                                          format: date-time
                                        estimada:
                                          type: string
                                          format: date-time
                                    idElemento:
                                      type: integer
                                    programada:
                                      type: boolean
                            estaciones:
                              type: array
                              items:
                                type: object
                                properties:
                                  tipo:
                                    type: object
                                    properties:
                                      id:
                                        type: integer
                                      nombre:
                                        type: string
                                  anden:
                                    type: object
                                    properties:
                                      id:
                                        type: integer
                                      nombre:
                                        type: string
                                  orden:
                                    type: integer
                                  tramo:
                                    type: object
                                    properties:
                                      id:
                                        type: integer
                                      orden:
                                        type: integer
                                  equipo:
                                    type: object
                                    properties:
                                      id:
                                        type: integer
                                      nombre:
                                        type: string
                                  nombre:
                                    type: string
                                  parada:
                                    type: boolean
                                  salida:
                                    type: object
                                    properties:
                                      programada:
                                        type: string
                                        format: date-time
                                      ultimaHoraRegistrada:
                                        type: string
                                        format: date-time
                                      distancia:
                                        type: number
                                        format: float
                                      velocidad:
                                        type: number
                                        format: float
                                      latitud:
                                        type: number
                                        format: float
                                      longitud:
                                        type: number
                                        format: float
                                      referencia:
                                        type: integer
                                      real:
                                        type: string
                                        format: date-time
                                  idPunto:
                                    type: integer
                                  llegada:
                                    type: object
                                  idElemento:
                                    type: integer
                                  programada:
                                    type: boolean
                                  segundos:
                                    type: integer
                  total:
                    type: integer
                example:
                  timestamp: 1736938591
                  results:
                    - arribo:
                        anden:
                          id: 1435
                          nombre: "2"
                        orden: 9
                        equipo:
                          id: 66
                          gpss:
                            - "57104"
                            - "57103"
                            - "57064"
                            - "57063"
                            - "528"
                            - "386"
                          nombre: "F134"
                          esElectrico: 1
                        nombre: "Bernal"
                        parada: true
                        salida:
                          programada: "2025-01-15T11:08:30.000Z"
                          estimada: "2025-01-15T11:09:45.000Z"
                        idPunto: 86
                        llegada:
                          programada: "2025-01-15T11:08:00.000Z"
                          estimada: "2025-01-15T11:09:15.000Z"
                        idElemento: 39
                        programada: true
                        segundos: 765
                      servicio:
                        numero: 2088
                        ramal:
                          id: 13
                          nombre: "Constitución-Bosques-Q"
                          tolerancia: 359
                          cabeceraFinal:
                            id: 43
                            nombre: "Bosques"
                            nombreCorto: "Bosques"
                          cabeceraInicial:
                            id: 93
                            nombre: "Constitución"
                            nombreCorto: "Plaza C."
                        gerencia:
                          id: 11
                          nombre: "Roca"
                        cancelacion: null
                        equipo:
                          id: 66
                          gpss:
                            - "57104"
                            - "57103"
                            - "57064"
                            - "57063"
                            - "528"
                            - "386"
                          nombre: "F134"
                          esElectrico: 1
                        oculto: false
                        sentido: 2
                        tipo:
                          id: 1
                          nombre: "Normal"
                          programado: true
                          clasificacion:
                            id: 1
                            nombre: "Pasajeros"
                          subclasificacion: 1
                        leyenda: null
                        location:
                          lat: -34.76366
                          long: -58.20929
                        id: "b69d0f98-c862-441e-b3fc-74fbfc9a07df"
                        desde:
                          estacion:
                            tipo:
                              id: 1
                              nombre: "Estación"
                            anden:
                              id: 1305
                              nombre: "1"
                            orden: 0
                            tramo:
                              id: 29
                              orden: 1671
                            equipo:
                              id: "66"
                              nombre: "F134"
                            nombre: "Bosques"
                            parada: true
                            salida:
                              programada: "2025-01-15T10:38:00.000Z"
                              ultimaHoraRegistrada: "2025-01-15T10:40:04.000Z"
                              distancia: 20
                              velocidad: 39
                              latitud: -34.8196339
                              longitud: -58.2299611
                              referencia: 20616
                              real: "2025-01-15T10:40:04.000Z"
                            idPunto: 93
                            llegada: {}
                            idElemento: 43
                            programada: true
                      hasta:
                        estacion:
                          tipo:
                            id: 1
                            nombre: "Estación"
                          orden: 17
                          tramo:
                            id: 17
                            orden: 10
                          equipo:
                            id: 66
                            gpss:
                              - "57104"
                              - "57103"
                              - "57064"
                              - "57063"
                              - "528"
                              - "386"
                            nombre: "F134"
                            esElectrico: 1
                          nombre: "Plaza C."
                          parada: true
                          salida:
                            programada: "2025-01-15T11:31:00.000Z"
                            estimada: "2025-01-15T11:32:15.000Z"
                          idPunto: 80
                          llegada:
                            programada: "2025-01-15T11:31:00.000Z"
                            estimada: "2025-01-15T11:32:15.000Z"
                          idElemento: 93
                          programada: true
                      estaciones:
                        - tipo:
                            id: 1
                            nombre: "Estación"
                          anden:
                            id: 1305
                            nombre: "1"
                          orden: 0
                          tramo:
                            id: 29
                            orden: 1671
                          equipo:
                            id: "66"
                            nombre: "F134"
                          nombre: "Bosques"
                          parada: true
                          salida:
                            programada: "2025-01-15T10:38:00.000Z"
                            ultimaHoraRegistrada: "2025-01-15T10:40:04.000Z"
                            distancia: 20
                            velocidad: 39
                            latitud: -34.8196339
                            longitud: -58.2299611
                            referencia: 20616
                            real: "2025-01-15T10:40:04.000Z"
                          idPunto: 93
                          llegada: {}
                          idElemento: 43
                          programada: true
                          segundos: -1109
                        - tipo:
                            id: 1
                            nombre: "Estación"
                          anden:
                            id: 1472
                            nombre: "2"
                          orden: 2
                          tramo:
                            id: 23
                            orden: 1478
                          equipo:
                            id: "66"
                            nombre: "F134"
                          nombre: "Sourigues"
                          parada: true
                          salida:
                            programada: "2025-01-15T10:42:00.000Z"
                            estimada: "2025-01-15T10:45:17.000Z"
                            real: "2025-01-15T10:45:33.000Z"
                            distancia: 260.1699
                            velocidad: 40
                            latitud: -34.8049491
                            longitud: -58.2118175
                            referencia: 17183
                          idPunto: 92
                          llegada:
                            programada: "2025-01-15T10:41:30.000Z"
                            estimada: "2025-01-15T10:44:47.000Z"
                            real: "2025-01-15T10:43:32.000Z"
                            distancia: 100.313
                            velocidad: 35
                            latitud: -34.8078936
                            longitud: -58.2134668
                            referencia: 17201
                          idElemento: 380
                          programada: true
                          segundos: -702
                  total: 2

        "401":
          description: Unauthorized access
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 401
                  message:
                    type: string
                    example: "Unauthorized"
                required:
                  - status
                  - message
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: hasta
          in: query
          required: false
          schema:
            type: number
        - name: fecha
          in: query
          required: false
          schema:
            type: string
            format: date
        - name: hora
          description: Hora en formato 24h HH:MM.
          in: query
          required: false
          schema:
            type: string
        - name: tipoBusqueda
          in: query
          required: false
          schema:
            enum: ["partida", "arribo"]
            default: partida
            type: string

  /public/app-estaciones/{id}:
    get:
      servers:
        - url: https://infoestaciones.sofse.gob.ar/
          description: Override base path for the GET /ping operation
      summary: GET estacion by id
      responses:
        "200":
          description: A successful response containing an array of station information
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    estacion:
                      type: string
                      example: "Plaza Constitución"
                    direccion:
                      type: string
                      example: "Av. Brasil 1128, CABA."
                    boleteria:
                      type: string
                      example: "24 hs."
                    cap:
                      type: string
                      example: "Lun. a sáb. de 5 a 21 hs. Dom. y fer. de 8 a 16 hs."
                    banos:
                      type: string
                      example: "SI"
                    ascensor:
                      type: string
                      example: "SI"
                    rampa:
                      type: string
                      example: "SI"
                    wifi:
                      type: string
                      example: "SI"
                    etb:
                      type: string
                      example: "Lunes a viernes, de 9 a 18 hs."
                    colectivos:
                      type: string
                      example: "4 - 9 - 10 - 12 - 17 - 28 - 39 - 45 - 46 - 51 - 53 - 59 - 60 - 61 - 62 - 65 - 67 - 70 - 79 - 84 - 91 - 95 - 96 - 97 - 98 - 100 - 102 - 129 - 133 - 134 - 143 - 148 - 151 - 154 - 168"
                    conexiones:
                      type: string
                      example: "Subte C (Estación Constitución) - Metrobus Sur - Estación Ecobici"
                    relevador:
                      type: string
                      example: "Marina"
                    estacion_id_unico:
                      type: integer
                      example: 93
                    linea_id:
                      type: integer
                      example: 11
                    terminal_sube:
                      type: string
                      example: "SI"
                  required:
                    - estacion
                    - direccion
                    - boleteria
                    - cap
                    - banos
                    - ascensor
                    - rampa
                    - wifi
                    - etb
                    - colectivos
                    - conexiones
                    - relevador
                    - estacion_id_unico
                    - linea_id
                    - terminal_sube
              example:
                - estacion: "Plaza Constitución"
                  direccion: "Av. Brasil 1128, CABA."
                  boleteria: "24 hs."
                  cap: "Lun. a sáb. de 5 a 21 hs. Dom. y fer. de 8 a 16 hs."
                  banos: "SI"
                  ascensor: "SI"
                  rampa: "SI"
                  wifi: "SI"
                  etb: "Lunes a viernes, de 9 a 18 hs."
                  colectivos: "4 - 9 - 10 - 12 - 17 - 28 - 39 - 45 - 46 - 51 - 53 - 59 - 60 - 61 - 62 - 65 - 67 - 70 - 79 - 84 - 91 - 95 - 96 - 97 - 98 - 100 - 102 - 129 - 133 - 134 - 143 - 148 - 151 - 154 - 168"
                  conexiones: "Subte C (Estación Constitución) - Metrobus Sur - Estación Ecobici"
                  relevador: "Marina"
                  estacion_id_unico: 93
                  linea_id: 11
                  terminal_sube: "SI"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
